### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by dergigi** [anitaposch/cto#1]
LICENSE file is missing in the repository. I'd encourage you to pick a permissive license, e.g. one of the licenses tagged as "free" (as in freedom) in this list: https://www.gnu.org/licenses/license-list.html

See the following for more info:

- https://blog.codinghorror.com/pick-a-license-any-license/
- https://choosealicense.com/
- https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by anitaonl** [comment]
Thank you. Added.
